# Generated by Django 3.0.7 on 2020-06-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_record',
            fields=[
                ('order_time', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('buy_id', models.CharField(max_length=5000, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('valid', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
