# Generated by Django 3.0.7 on 2020-06-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAG', '0002_auto_20200628_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_record',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_record',
            name='total',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
